=== schupeter/schemas/hash/1.0/hashtable_measure_count.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- edited with XMLSpy v2006 sp2 U (http://www.altova.com) by Peter Schut (Agriculture & Agri-Food Canada) -->
<!--W3C Schema generated by XMLSpy v2006 sp2 U (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<!-- =============================================================
		simple elements 
	============================================================== -->
	<xs:element name="Abstract" type="xs:string"/>
	<xs:element name="AttributeName" type="xs:string"/>
	<xs:element name="Description" type="xs:string"/>
	<xs:element name="Documentation" type="xs:anyURI"/>
	<xs:element name="Identifier" type="xs:string"/>
	<xs:element name="Key" type="xs:string"/>
	<xs:element name="Title" type="xs:string"/>
	<xs:element name="GE" type="xs:string"/>
	<xs:element name="LT" type="xs:string"/>
	<xs:element name="Value" type="xs:string"/>
	<!-- =============================================================
		simple base types
	============================================================== -->
	<xs:element name="Hash">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Title"/>
				<xs:element ref="Description"/>
				<xs:element name="KeyDescriptions" type="KeyDescriptionsType"/>
				<xs:element name="ValueDescription" type="ValueDescriptionType"/>
				<xs:element name="Mapping" type="MappingTableType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- =========================================================== -->
	<xs:complexType name="KeyDescriptionsType">
		<xs:sequence>
			<xs:element name="Attribute" type="KeyAttributeType"/>
		</xs:sequence>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="KeyAttributeType">
		<xs:sequence>
			<xs:element ref="AttributeName"/>
			<xs:element ref="Title"/>
			<xs:element ref="Description"/>
			<xs:element ref="Documentation"/>
			<xs:element name="Values" type="KeyValuesType"/>
		</xs:sequence>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="KeyValuesType">
		<xs:choice>
			<xs:element name="Count" type="CountType"/>
			<xs:element name="Measure" type="MeasureType"/>
		</xs:choice>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="CountType">
		<xs:sequence/>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="http://www.w3.org/TR/xmlschema-2/#integer"/>
					<xs:enumeration value="http://www.w3.org/TR/xmlschema-2/#decimal"/>
					<xs:enumeration value="http://www.w3.org/TR/xmlschema-2/#float"/>
					<xs:enumeration value="http://www.w3.org/TR/xmlschema-2/#double"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="length" type="xs:nonNegativeInteger" use="required"/>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="MeasureType">
		<xs:sequence>
			<xs:element name="UOM" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="http://www.w3.org/TR/xmlschema-2/#decimal"/>
					<xs:enumeration value="http://www.w3.org/TR/xmlschema-2/#float"/>
					<xs:enumeration value="http://www.w3.org/TR/xmlschema-2/#double"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="length" type="xs:nonNegativeInteger" use="required"/>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="MappingTableType">
		<xs:sequence>
			<xs:element name="Range" type="RangeType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="RangeType">
		<xs:sequence>
			<xs:element ref="GE"/>
			<xs:element ref="LT"/>
			<xs:element ref="Value"/>
		</xs:sequence>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="ValueDescriptionType">
		<xs:sequence>
			<xs:element name="Attribute" type="ValueAttributeType"/>
		</xs:sequence>
		<!-- =========================================================== -->
	</xs:complexType>
	<xs:complexType name="ValueAttributeType">
		<xs:sequence>
			<xs:element ref="AttributeName"/>
			<xs:element ref="Title"/>
			<xs:element ref="Description"/>
			<xs:element ref="Documentation"/>
			<xs:element name="Values" type="ValueValuesType"/>
		</xs:sequence>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="ValueValuesType">
		<xs:sequence>
			<xs:element name="Ordinal" type="OrdinalType"/>
		</xs:sequence>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="OrdinalType">
		<xs:sequence>
			<xs:element name="Classes" type="OrdinalClassesType"/>
		</xs:sequence>
		<xs:attribute name="type" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:anyURI">
					<xs:enumeration value="http://www.w3.org/TR/xmlschema-2/#string"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="length" type="xs:string" use="required"/>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="OrdinalClassesType">
		<xs:choice>
			<xs:element name="Value" type="OrdinalValueType" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="OrdinalValueType">
		<xs:complexContent>
			<xs:extension base="NominalValueType">
				<xs:attribute name="rank" type="xs:nonNegativeInteger" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- =========================================================== -->
	<xs:complexType name="NominalValueType">
		<xs:sequence>
			<xs:element ref="Identifier"/>
			<xs:element ref="Title"/>
			<xs:element ref="Abstract"/>
			<xs:element ref="Documentation"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== schupeter/schemas/hash/1.0b/examples/hashtable_lsrs_egdd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../stylesheets/hash2html2.xsl"?>
<Hash xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hashtable_measure_count.xsd">
	<Title>LSRS EGDD Estimate</Title>
	<Description>This transformation will convert EGDD values to an LSRS class.</Description>
	<KeyDescriptions>
		<Attribute>
			<AttributeName>EGDD</AttributeName>
			<Title>EGDD</Title>
			<Description>Effective Growing Degree Days.</Description>
			<Documentation></Documentation>
			<Values>
				<Measure type="http://www.w3.org/TR/xmlschema-2/#integer" length="5"/>
			</Values>
		</Attribute>
	</KeyDescriptions>
	<ValueDescription>
		<Attribute>
			<AttributeName>LSRS_EGDD</AttributeName>
			<Title>LSRS class based on EGDD values</Title>
			<Description>LSRS class estimate based on EGDD values.</Description>
			<Documentation></Documentation>
			<Values>
				<Ordinal type="http://www.w3.org/TR/xmlschema-2/#string" length="1">
					<Classes>
						<Value rank="1">
							<Identifier>1</Identifier>
							<Title>Class 1</Title>
							<Abstract>Class 1</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="2">
							<Identifier>2</Identifier>
							<Title>Class 2</Title>
							<Abstract>Class 2</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="3">
							<Identifier>3</Identifier>
							<Title>Class 3</Title>
							<Abstract>Class 3</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="4">
							<Identifier>4</Identifier>
							<Title>Class 4</Title>
							<Abstract>Class 4</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="5">
							<Identifier>5</Identifier>
							<Title>Class 5</Title>
							<Abstract>Class 5</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="6">
							<Identifier>6</Identifier>
							<Title>Class 6</Title>
							<Abstract>Class 6</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="7">
							<Identifier>7</Identifier>
							<Title>Class 7</Title>
							<Abstract>Class 7</Abstract>
							<Documentation></Documentation>
						</Value>
					</Classes>
				</Ordinal>
			</Values>
		</Attribute>
	</ValueDescription>
	<Mapping>
		<Range>
			<GE>1435</GE>
			<LT>9999</LT>
			<Value>1</Value>
		</Range>
		<Range>
			<GE>1260</GE>
			<LT>1435</LT>
			<Value>2</Value>
		</Range>
		<Range>
			<GE>1135</GE>
			<LT>1260</LT>
			<Value>3</Value>
		</Range>
		<Range>
			<GE>1015</GE>
			<LT>1135</LT>
			<Value>4</Value>
		</Range>
		<Range>
			<GE>900</GE>
			<LT>1015</LT>
			<Value>5</Value>
		</Range>
		<Range>
			<GE>0</GE>
			<LT>900</LT>
			<Value>6</Value>
		</Range>
	</Mapping>
</Hash>

=== schupeter/schemas/hash/1.0b/examples/hashtable_lsrs_ppe.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../stylesheets/hash2html2.xsl"?>
<Hash xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hashtable_measure_count.xsd">
	<Title>LSRS PPE Estimate</Title>
	<Description>This transformation will take P-PE values and estimate an LSRS class.</Description>
	<KeyDescriptions>
		<Attribute>
			<AttributeName>PPE</AttributeName>
			<Title>P-PE</Title>
			<Description>Precipitation minus Potential Evapotranspiration.</Description>
			<Documentation></Documentation>
			<Values>
				<Measure type="http://www.w3.org/TR/xmlschema-2/#integer" length="5"/>
			</Values>
		</Attribute>
	</KeyDescriptions>
	<ValueDescription>
		<Attribute>
			<AttributeName>LSRS_PPE</AttributeName>
			<Title>LSRS class based on PPE</Title>
			<Description>LSRS class estimate based on P-PE.</Description>
			<Documentation></Documentation>
			<Values>
				<Ordinal type="http://www.w3.org/TR/xmlschema-2/#string" length="1">
					<Classes>
						<Value rank="1">
							<Identifier>1</Identifier>
							<Title>Class 1</Title>
							<Abstract>Class 1</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="2">
							<Identifier>2</Identifier>
							<Title>Class 2</Title>
							<Abstract>Class 2</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="3">
							<Identifier>3</Identifier>
							<Title>Class 3</Title>
							<Abstract>Class 3</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="4">
							<Identifier>4</Identifier>
							<Title>Class 4</Title>
							<Abstract>Class 4</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="5">
							<Identifier>5</Identifier>
							<Title>Class 5</Title>
							<Abstract>Class 5</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="6">
							<Identifier>6</Identifier>
							<Title>Class 6</Title>
							<Abstract>Class 6</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="7">
							<Identifier>7</Identifier>
							<Title>Class 7</Title>
							<Abstract>Class 7</Abstract>
							<Documentation></Documentation>
						</Value>
					</Classes>
				</Ordinal>
			</Values>
		</Attribute>
	</ValueDescription>
	<Mapping>
		<Range>
			<GE>-250</GE>
			<LT>1000</LT>
			<Value>1</Value>
		</Range>
		<Range>
			<GE>-350</GE>
			<LT>-250</LT>
			<Value>2</Value>
		</Range>
		<Range>
			<GE>-425</GE>
			<LT>-350</LT>
			<Value>3</Value>
		</Range>
		<Range>
			<GE>-500</GE>
			<LT>-425</LT>
			<Value>4</Value>
		</Range>
		<Range>
			<GE>-2000</GE>
			<LT>-500</LT>
			<Value>5</Value>
		</Range>
	</Mapping>
</Hash>

=== schupeter/schemas/hash/1.0/examples/hashtable_measure_count.xml
<?xml version="1.0" encoding="UTF-8"?>

Should be converted to a Numeric Classification file!

<?xml-stylesheet type="text/xsl" href="../xsl/hash2html2.xsl"?>
<Hash xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="hashtable_measure_count.xsd">
	<Title>SLC Surface Material Generalization #1</Title>
	<Description>This transformation will generalize the SLC Surface Material field into five new classes.</Description>
	<KeyDescriptions>
		<Attribute>
			<AttributeName>material</AttributeName>
			<Title>Surface Material</Title>
			<Description>Surface material includes the abiotic material at the earth's surface.</Description>
			<Documentation>http://sis.agr.gc.ca/cansis/nsdb/ecostrat/surface_material.html</Documentation>
			<Values>
				<Count type="http://www.w3.org/TR/xmlschema-2/#integer" length="3"/>
			</Values>
		</Attribute>
	</KeyDescriptions>
	<ValueDescription>
		<Attribute>
			<AttributeName>material</AttributeName>
			<Title>Surface Material</Title>
			<Description>Surface material includes the abiotic material at the earth's surface.  Generated from Surface Material in the original database.</Description>
			<Documentation>http://sis.agr.gc.ca/cansis/nsdb/ecostrat/surface_material.html</Documentation>
			<Values>
				<Ordinal type="http://www.w3.org/TR/xmlschema-2/#string" length="3">
					<Classes>
						<Value rank="1">
							<Identifier>Low</Identifier>
							<Title>Low Risk</Title>
							<Abstract>Low risk</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="2">
							<Identifier>Medium</Identifier>
							<Title>Medium Risk</Title>
							<Abstract>Medium risk</Abstract>
							<Documentation></Documentation>
						</Value>
						<Value rank="3">
							<Identifier>High</Identifier>
							<Title>High Risk</Title>
							<Abstract>High risk</Abstract>
							<Documentation></Documentation>
						</Value>
					</Classes>
				</Ordinal>
			</Values>
		</Attribute>
	</ValueDescription>
	<Mapping>
		<Range>
			<GE>0</GE>
			<LT>10</LT>
			<Value>Low</Value>
		</Range>
		<Range>
			<GE>10</GE>
			<LT>25</LT>
			<Value>Medium</Value>
		</Range>
		<Range>
			<GE>25</GE>
			<LT>100</LT>
			<Value>High</Value>
		</Range>
	</Mapping>
</Hash>
