=== schupeter/schemas/classify/1.0/NumericClassification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by Peter Schut (Agriculture Canada) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- ========= top level element =================================== -->
	<xs:element name="NumericClassification">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Title"/>
				<xs:element ref="Abstract"/>
				<xs:element ref="AttributeToRank"/>
				<xs:element ref="ResultantValues"/>
				<xs:element ref="RankingScheme"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<!-- ========= other elements ==================================== -->
	<xs:element name="Abstract" type="xs:string"/>
	<xs:element name="AttributeToRank">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Title"/>
				<xs:element ref="Abstract"/>
				<xs:element ref="Values"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Classes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Title"/>
				<xs:element ref="Abstract" minOccurs="0"/>
				<xs:element ref="Documentation" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Documentation" type="xs:anyURI"/>
	<xs:element name="LastRange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StartPoint"/>
				<xs:element name="EndPoint" minOccurs="0">
					<xs:complexType>
						<xs:attribute name="include"/>
					</xs:complexType>
				</xs:element>
				<xs:element ref="Identifier"/>
				<xs:element ref="Title"/>
				<xs:element ref="Abstract" minOccurs="0"/>
				<xs:element ref="Documentation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="rank" type="xs:integer" use="required"/>
			<xs:attribute name="color" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Exception">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="OriginalValue" maxOccurs="unbounded"/>
				<xs:element ref="Identifier"/>
				<xs:element ref="Title"/>
			</xs:sequence>
			<xs:attribute name="color" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FirstRange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StartPoint" minOccurs="0"/>
				<xs:element ref="Identifier"/>
				<xs:element ref="Title"/>
				<xs:element ref="Abstract" minOccurs="0"/>
				<xs:element ref="Documentation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="rank" type="xs:string" use="required"/>
			<xs:attribute name="color" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Identifier" type="xs:string"/>
	<xs:element name="LongForm" type="xs:string"/>
	<xs:element name="MidRange">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StartPoint"/>
				<xs:element ref="Identifier"/>
				<xs:element ref="Title"/>
				<xs:element ref="Abstract" minOccurs="0"/>
				<xs:element ref="Documentation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="rank" type="xs:integer" use="required"/>
			<xs:attribute name="color" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Missing">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Identifier"/>
				<xs:element ref="Title"/>
			</xs:sequence>
			<xs:attribute name="color" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Ordinal">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Classes"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:anyURI" use="required"/>
			<xs:attribute name="length" type="xs:integer" use="required"/>
			<xs:attribute name="decimals" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="OriginalValue" type="xs:string"/>
	<xs:element name="RankingScheme">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FirstRange"/>
				<xs:element ref="MidRange" maxOccurs="unbounded"/>
				<xs:element ref="LastRange"/>
				<xs:element ref="Missing" minOccurs="0"/>
				<xs:element ref="Exception" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ResultantValues">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Ordinal"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ShortForm" type="xs:string"/>
	<xs:element name="StartPoint">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:float">
					<xs:attribute name="include" type="xs:boolean" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Title" type="xs:string"/>
	<xs:element name="UOM">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ShortForm"/>
				<xs:element ref="LongForm"/>
			</xs:sequence>
			<xs:attribute name="reference" type="xs:anyURI"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Count">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="UOM"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Measure">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="UOM"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Values">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="Count"/>
				<xs:element ref="Measure"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== schupeter/schemas/classify/1.0/oldexamples/temperature001xsl.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/stylesheets/classify/1.0/NumericClassification.xsl"?>
<NumericClassification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/schemas/classify/1.0/NumericClassification.xsd">
	<Title>Temperature Classification #1</Title>
	<Abstract>This transformation will rank temperature data into 7 classes.</Abstract>
	<AttributeToRank>
		<Title>Temperature</Title>
		<Abstract>Temperature</Abstract>
		<Measure type="http://www.w3.org/TR/xmlschema-2/#float" length="3">
			<UOM reference="http://unitsofmeasure.org/">C</UOM>
		</Measure>
	</AttributeToRank>
	<RankingScheme>
		<FirstRange rank="1">
			<Identifier>EC</Identifier>
			<Title>Extremely Cold</Title>
		</FirstRange>
		<Range rank="2">
			<StartPoint include="true">-30</StartPoint>
			<Identifier>VC</Identifier>
			<Title>Very Cold</Title>
		</Range>
		<Range rank="3">
			<StartPoint include="true">-20</StartPoint>
			<Identifier>C</Identifier>
			<Title>Cold</Title>
		</Range>
		<Range rank="4">
			<StartPoint include="true">-10</StartPoint>
			<Identifier>L</Identifier>
			<Title>Cool</Title>
		</Range>
		<Range rank="5">
			<StartPoint include="true">0</StartPoint>
			<Identifier>M</Identifier>
			<Title>Mild</Title>
		</Range>
		<Range rank="6">
			<StartPoint include="true">10</StartPoint>
			<Identifier>W</Identifier>
			<Title>Warm</Title>
		</Range>
		<Range rank="7">
			<StartPoint include="true">20</StartPoint>
			<Identifier>H</Identifier>
			<Title>Hot</Title>
		</Range>
    <Missing>
			<Identifier>nil</Identifier>
			<Title>Missing</Title>
    </Missing>
    <Exception>
      <OriginalValue>n/a</OriginalValue>
			<Identifier>n/a</Identifier>
			<Title>Not Available</Title>
    </Exception>
	</RankingScheme>
</NumericClassification>

=== schupeter/schemas/classify/1.0/examples/temperature001obsolescent.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/schemas/classify/1.0/stylesheets/NumericClassification.xsl"?>
<NumericClassification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../NumericClassification.xsd">
	<Title>Temperature Classification #1</Title>
	<Abstract>This transformation will rank temperature data into 7 classes.</Abstract>
	<AttributeToRank>
		<Title>Temperature</Title>
		<Abstract>Temperature</Abstract>
		<Values>
			<Measure>
				<UOM reference="http://unitsofmeasure.org/">
					<ShortForm>Â°C</ShortForm>
					<LongForm>degrees centigrade</LongForm>
				</UOM>
			</Measure>
		</Values>
	</AttributeToRank>
	<ResultantValues>
		<Ordinal type="http://www.w3.org/TR/xmlschema-2/#string" length="3" decimals="0">
			<Classes>
				<Title>Canadian Temperature Guide</Title>
				<Abstract>Monthly normals temperature classes for Canada</Abstract>
				<Documentation>
				</Documentation>
			</Classes>
		</Ordinal>
	</ResultantValues>
	<RankingScheme>
		<FirstRange rank="1" color="CCFFCC">
			<Identifier>EC</Identifier>
			<Title>Extremely Cold</Title>
		</FirstRange>
		<MidRange rank="2" color="CCFFCC">
			<StartPoint include="true">-30</StartPoint>
			<Identifier>VC</Identifier>
			<Title>Very Cold</Title>
		</MidRange>
		<MidRange rank="3" color="CCFFCC">
			<StartPoint include="true">-20</StartPoint>
			<Identifier>C</Identifier>
			<Title>Cold</Title>
		</MidRange>
		<MidRange rank="4" color="CCFFCC">
			<StartPoint include="true">-10</StartPoint>
			<Identifier>L</Identifier>
			<Title>Cool</Title>
		</MidRange>
		<MidRange rank="5" color="CCFFCC">
			<StartPoint include="true">0</StartPoint>
			<Identifier>M</Identifier>
			<Title>Mild</Title>
		</MidRange>
		<MidRange rank="6" color="CCFFCC">
			<StartPoint include="true">10</StartPoint>
			<Identifier>W</Identifier>
			<Title>Warm</Title>
		</MidRange>
		<LastRange rank="7" color="CCFFCC">
			<StartPoint include="true">20</StartPoint>
			<Identifier>H</Identifier>
			<Title>Hot</Title>
		</LastRange>
		<Missing color="CCFFCC">
			<Identifier>nil</Identifier>
			<Title>Missing</Title>
		</Missing>
		<Exception color="CCFFCC">
			<OriginalValue>n/a</OriginalValue>
			<Identifier>n/a</Identifier>
			<Title>Not Available</Title>
		</Exception>
	</RankingScheme>
</NumericClassification>

=== schupeter/schemas/classify/1.0/oldexamples/oldtemperature001xsl.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/stylesheets/classify/1.0/NumericClassification.xsl"?>
<NumericClassification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/schemas/classify/1.0/NumericClassification.xsd">
	<Title>Temperature Classification #1</Title>
	<Abstract>This transformation will rank temperature data into 6 classes.</Abstract>
	<AttributeToRank>
		<Title>Temperature</Title>
		<Abstract>Temperature</Abstract>
		<Measure type="http://www.w3.org/TR/xmlschema-2/#float" length="3">
			<UOM reference="http://en.wikipedia.org/wiki/Celsius">Â°C</UOM>
		</Measure>
	</AttributeToRank>
	<RankingScheme>
		<FirstRange rank="1">
			<StartPoint include="true">-30</StartPoint>
			<Identifier>EC</Identifier>
			<Title>Extremely Cold</Title>
		</FirstRange>
		<MidRange rank="2">
			<StartPoint include="true">-20</StartPoint>
			<Identifier>VC</Identifier>
			<Title>Very Cold</Title>
		</MidRange>
		<MidRange rank="3">
			<StartPoint include="true">-10</StartPoint>
			<Identifier>C</Identifier>
			<Title>Cold</Title>
		</MidRange>
		<MidRange rank="4">
			<StartPoint include="true">0</StartPoint>
			<Identifier>M</Identifier>
			<Title>Moderate</Title>
		</MidRange>
		<LastRange rank="5">
			<StartPoint include="true">10</StartPoint>
			<EndPoint include="true">30</EndPoint>
			<Identifier>W</Identifier>
			<Title>Warm</Title>
		</LastRange>
	</RankingScheme>
</NumericClassification>
