=== schupeter/schemas/palette/palette.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Palette">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Title"/>
				<xs:element ref="Abstract"/>
				<xs:element ref="ColorSet"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Title" type="xs:string"/>
	<xs:element name="Abstract" type="xs:string"/>
	<xs:element name="ColorSet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Color" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="ramp"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Color">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="id" type="xs:integer" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== schupeter/schemas/palette/1.0/examples/palette_soil_name_v2_kind_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../stylesheets/palette2html.xsl"?>
<Palette xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../palette.xsd">
	<Title>Kind of Material (KIND)</Title>
	<Abstract>Colors used to map Soil Name Table v2 Kind of Material.</Abstract>
	<ColorSet ramp="false">
		<Color id="M" value="A87000" tip="Mineral"/>
		<Color id="O" value="FF99EB" tip="Organic"/>
		<Color id="N" value="E04A2C" tip="Non-soil"/>
		<Color id="U" value="B2B2B2" tip="Urban"/>
	</ColorSet>
</Palette>

=== schupeter/schemas/palette/1.0/examples/palette_ecozones_v1_names.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../stylesheets/palette2html.xsl"?>
<Palette xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../palette.xsd">
	<Title>Ecozone Colors</Title>
	<Abstract>Colors used on the Ecozones of Canada map</Abstract>
	<ColorSet ramp="false">
		<Color id="1" value="CCFFFF" tip="Arctic Cordillera" />
		<Color id="2" value="99CCCC" tip="Northern Arctic" />
		<Color id="3" value="0099CC" tip="Southern Arctic" />
		<Color id="4" value="CCCCCC" tip="Taiga Plains" />
		<Color id="5" value="999999" tip="Taiga Shield" />
		<Color id="6" value="66CC66" tip="Boreal Shield" />
		<Color id="7" value="66CCCC" tip="Atlantic Maritime" />
		<Color id="8" value="CCCC99" tip="Mixedwood Plains" />
		<Color id="9" value="CCFFCC" tip="Boreal Plains" />
		<Color id="10" value="FFFF99" tip="Prairies" />
		<Color id="11" value="CC99CC" tip="Taiga Cordillera" />
		<Color id="12" value="9966CC" tip="Boreal Cordillera" />
		<Color id="13" value="006600" tip="Pacific Maritime" />
		<Color id="14" value="99CC00" tip="Montane Cordillera" />
		<Color id="15" value="CCFF99" tip="Hudson Plains" />
	</ColorSet>
</Palette>
