=== schupeter/schemas/palettes_obsolete/1.0/palette.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Peter Schut (Agriculture Canada) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Abstract" type="xs:string"/>
	<xs:element name="ColorSet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Color" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="ramp" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Color">
		<xs:complexType>
			<xs:attribute name="id" type="xs:string" use="required"/>
			<xs:attribute name="value" type="xs:string" use="required"/>
			<xs:attribute name="tip" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Palette">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Title"/>
				<xs:element ref="Abstract"/>
				<xs:element ref="ColorSet"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Title" type="xs:string"/>
</xs:schema>

=== schupeter/schemas/palettes_obsolete/1.0/examples/palette_slc_v2.2_kindmat_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../stylesheets/palette2html.xsl"?>
<Palette xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../palette.xsd">
	<Title>Kind of Material</Title>
	<Abstract>Colors used to map SLC v2.2 Kind of Material (KINDMAT).</Abstract>
	<ColorSet ramp="false">
		<Color id="SO" value="A87000" tip="Soil"/>
		<Color id="OR" value="FF99EB" tip="Organic"/>
		<Color id="R1" value="F9957E" tip="Soft rock"/>
		<Color id="R2" value="E77B62" tip="Hard rock, acidic"/>
		<Color id="R3" value="D55E43" tip="Hard rock, basic"/>
		<Color id="R4" value="C33819" tip="Hard rock"/>
		<Color id="F" value="C33819" tip="Rock field"/>
		<Color id="UR" value="EFEF0E" tip="Urban"/>
		<Color id="IC" value="FFFFFF" tip="Ice and snow"/>
		<Color id="WA" value="002AFF" tip="Water"/>
	</ColorSet>
</Palette>

=== schupeter/schemas/palettes_obsolete/1.0/examples/palette_soil_name_v2_order_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../stylesheets/palette2html.xsl"?>
<Palette xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../palette.xsd">
	<Title>Soil Order</Title>
	<Abstract>Colors used to map Soil Name Table v2 Soil Order (ORDER3).</Abstract>
	<ColorSet ramp="false">
		<Color id="BR" value="B08D0B" tip="Brunisol"/>
		<Color id="CH" value="DC660F" tip="Chernozem"/>
		<Color id="CY" value="3E88E1" tip="Cryosol"/>
		<Color id="GL" value="2E6EAE" tip="Gleysol"/>
		<Color id="LU" value="E5E56B" tip="Luvisol"/>
		<Color id="OR" value="FF99EB" tip="Organic"/>
		<Color id="PZ" value="064A11" tip="Podzol"/>
		<Color id="RG" value="5E5999" tip="Regosol"/>
		<Color id="SZ" value="B31400" tip="Solonetz"/>
		<Color id="VE" value="B6A071" tip="Vertisol"/>
		<Color id="-" value="B2B2B2" tip="n/a"/>
	</ColorSet>
</Palette>
