=== schupeter/schemas/part/1.1/part.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:part="http://schemas.agr.gc.ca/part/1.1" xmlns:tjs="http://www.opengis.net/tjs/1.0" targetNamespace="http://schemas.agr.gc.ca/part/1.1" elementFormDefault="unqualified" version="1.1.0" xml:lang="en">
	<annotation>
		<appinfo>$Id: part.xsd 2010-03-30 $</appinfo>
		<documentation>
			<description>This XML Schema encodes a Polygon Attribute Reallocation Table (PART).</description>
			<copyright>Copyright (c) 2010 Agriculture and Agri-Food Canada, All Rights Reserved. </copyright>
		</documentation>
	</annotation>
	<!-- =============================================================
		includes and imports
	============================================================== -->
	<import namespace="http://www.opengis.net/tjs/1.0" schemaLocation="/schemas/tjs/1.0/tjsJoinData_response.xsd"/>
	<!-- =============================================================
		simple elements 
	============================================================== -->
	<element name="PART">
		<annotation>
			<documentation>Polygon Attribute Reallocation Table</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element ref="part:Source">
					<annotation>
						<documentation>Source polygon spatial database </documentation>
					</annotation>
				</element>
				<element ref="part:Target">
					<annotation>
						<documentation>Target polygon spatial database</documentation>
					</annotation>
				</element>
				<element ref="part:Rowset">
					<annotation>
						<documentation>Reallocation table</documentation>
					</annotation>
				</element>
			</sequence>
		</complexType>
	</element>
	<!-- =========================================================== -->
	<element name="Source">
		<complexType>
			<sequence>
				<element name="Framework" type="tjs:FrameworkType">
					<annotation>
						<documentation>Spatial database identification</documentation>
					</annotation>
				</element>
				<element ref="part:Filter">
					<annotation>
						<documentation>Description of the spatial filter which was applied to the source dataset.</documentation>
					</annotation>
				</element>
			</sequence>
		</complexType>
	</element>
	<!-- =========================================================== -->
	<element name="Target">
		<complexType>
			<sequence>
				<element name="Framework" type="tjs:FrameworkType">
					<annotation>
						<documentation>Spatial database identification</documentation>
					</annotation>
				</element>
				<element ref="part:Filter">
					<annotation>
						<documentation>Description of the spatial filter which was applied to the target dataset.</documentation>
					</annotation>
				</element>
			</sequence>
		</complexType>
	</element>
	<!-- =========================================================== -->
	<element name="Filter">
		<complexType>
			<sequence>
				<element name="Title" type="string">
					<annotation>
						<documentation>Title of the spatial filter.</documentation>
					</annotation>
				</element>
				<element name="Abstract" type="string">
					<annotation>
						<documentation>Abstract of the spatial filter.</documentation>
					</annotation>
				</element>
			</sequence>
		</complexType>
	</element>
	<!-- =========================================================== -->
	<element name="Rowset">
		<complexType>
			<sequence>
				<element ref="part:Row" maxOccurs="unbounded">
					<annotation>
						<documentation>Table row</documentation>
					</annotation>
				</element>
			</sequence>
		</complexType>
	</element>
	<element name="Row">
		<complexType>
			<sequence>
				<element ref="part:S"/>
				<element ref="part:T"/>
				<element ref="part:P"/>
			</sequence>
		</complexType>
	</element>
	<!-- =========================================================== -->
	<element name="S" type="string">
		<annotation>
			<documentation>Source polygon identifier from the Source Framework GeolinkageField</documentation>
		</annotation>
	</element>
	<element name="T" type="string">
		<annotation>
			<documentation>Target polygon identifier from the Target Framework GeolinkageField</documentation>
		</annotation>
	</element>
	<element name="P">
		<annotation>
			<documentation>Portion of the source polygon information which shall be allocated to the target polygon </documentation>
		</annotation>
		<simpleType>
			<restriction base="decimal">
				<minInclusive value="0"/>
				<maxInclusive value="1"/>
			</restriction>
		</simpleType>
	</element>
</schema>

=== schupeter/schemas/part/1.1/examples/PR_to_PR-SLC311_Reallocation_Table_20080222b.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/schemas/part/1.1/xsl/part2html.xsl"?>
<PART xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/schemas/part/1.1/PART.xsd">
	<Title>Reallocate Province data to SLC v3.1.1.</Title>
	<Source>
		<Framework>
			<FrameworkURI>http://sis.agr.gc.ca/nsdb/prov/2004</FrameworkURI>
			<Organization>Agriculture and Agri-Food Canada</Organization>
			<Title>Provinces</Title>
			<Abstract>Provinces (based on CRAM regions for 2004)</Abstract>
			<ReleaseDate>2008-01-01</ReleaseDate>
			<Documentation/>
			<FrameworkKey>PR</FrameworkKey>
			<BoundingBox>
				<Minimum>
					<Latitude>43</Latitude>
					<Longitude>-145</Longitude>
				</Minimum>
				<Maximum>
					<Latitude>90</Latitude>
					<Longitude>-50</Longitude>
				</Maximum>
			</BoundingBox>
		</Framework>
		<Filter>
			<Abstract>none</Abstract>
		</Filter>
	</Source>
	<Target>
		<Framework>
			<FrameworkURI>http://sis.agr.gc.ca/nsdb/slcprov/v3.1.1</FrameworkURI>
			<Organization>Agriculture and Agri-Food Canada</Organization>
			<Title>Soil Landscapes of Canada, provincial</Title>
			<Abstract>Soil Landscapes of Canada, intersected with province boundaries.</Abstract>
			<ReleaseDate>2006-04-27</ReleaseDate>
			<Documentation>http://sis.agr.gc.ca/cansis/nsdb/slc/v3.1.1/intro.html</Documentation>
			<FrameworkKey>pr-sl</FrameworkKey>
			<BoundingBox>
				<Minimum>
					<Latitude>43</Latitude>
					<Longitude>-145</Longitude>
				</Minimum>
				<Maximum>
					<Latitude>90</Latitude>
					<Longitude>-50</Longitude>
				</Maximum>
			</BoundingBox>
		</Framework>
		<Filter>
			<Abstract>All water bodies as defined in the Hydro coverage</Abstract>
		</Filter>
	</Target>
	<Rowset>
<Row><S>AL</S><T>AL1016002</T><P>0.0010324666785084</P></Row>
<Row><S>AL</S><T>AL1016003</T><P>0.0012729167252126</P></Row>
<Row><S>AL</S><T>AL1017026</T><P>0.0059880889405582</P></Row>
<Row><S>AL</S><T>AL1018001</T><P>0.0004820919618872</P></Row>
<Row><S>AL</S><T>AL1018002</T><P>0.0012944792613394</P></Row>
<Row><S>AL</S><T>AL1018003</T><P>0.0005912538264407</P></Row>
<Row><S>AL</S><T>AL1018004</T><P>0.0007127895853403</P></Row>
<Row><S>AL</S><T>AL1018005</T><P>0.0026945069982847</P></Row>
<Row><S>AL</S><T>AL1018006</T><P>0.0016109055900875</P></Row>
<Row><S>AL</S><T>AL1018007</T><P>0.001616722526541</P></Row>
<Row><S>AL</S><T>AL1018008</T><P>0.0008859631334373</P></Row>
<Row><S>AL</S><T>AL1019004</T><P>0.0021357491998842</P></Row>
<Row><S>AL</S><T>AL583013</T><P>0.0014851846852481</P></Row>
<Row><S>AL</S><T>AL586001</T><P>0.0044428540174729</P></Row>
<Row><S>AL</S><T>AL586002</T><P>0.0058932489516042</P></Row>
<Row><S>AL</S><T>AL586004</T><P>0.001945800499145</P></Row>
<Row><S>AL</S><T>AL586005</T><P>0.0032836552867649</P></Row>
<Row><S>AL</S><T>AL586010</T><P>0.0008094409616082</P></Row>
<Row><S>AL</S><T>AL586011</T><P>0.001019005862317</P></Row>
<Row><S>AL</S><T>AL586012</T><P>0.0020501930227056</P></Row>
<Row><S>AL</S><T>AL586013</T><P>0.0022546729262853</P></Row>
<Row><S>AL</S><T>AL586014</T><P>0.0006836496042213</P></Row>
<Row><S>AL</S><T>AL586015</T><P>0.0007973114939916</P></Row>
<Row><S>AL</S><T>AL586016</T><P>0.0035197070804665</P></Row>
<Row><S>AL</S><T>AL587001</T><P>0.0032175527644772</P></Row>
<Row><S>AL</S><T>AL587003</T><P>0.0014293997312426</P></Row>
<Row><S>AL</S><T>AL587005</T><P>0.0003520038108612</P></Row>
<Row><S>AL</S><T>AL587006</T><P>0.0005370373501019</P></Row>
<Row><S>AL</S><T>AL588004</T><P>0.0010078394253761</P></Row>
<Row><S>AL</S><T>AL588005</T><P>0.0014794012180844</P></Row>
<Row><S>AL</S><T>AL588007</T><P>0.0016526545991563</P></Row>
<Row><S>AL</S><T>AL588008</T><P>0.0004524159120894</P></Row>
<Row><S>AL</S><T>AL588009</T><P>0.0022510640622107</P></Row>
<Row><S>AL</S><T>AL588010</T><P>0.0010513635503137</P></Row>
<Row><S>AL</S><T>AL588011</T><P>0.0003714734935575</P></Row>
<Row><S>AL</S><T>AL588012</T><P>0.0009328257153024</P></Row>
<Row><S>AL</S><T>AL588013</T><P>0.0007885684366967</P></Row>
<Row><S>AL</S><T>AL588014</T><P>0.0017100134628666</P></Row>
<Row><S>AL</S><T>AL589002</T><P>0.001054623830861</P></Row>
<Row><S>AL</S><T>AL590001</T><P>0.002487660680268</P></Row>
<Row><S>AL</S><T>AL590002</T><P>0.0007053224537712</P></Row>
<Row><S>AL</S><T>AL590003</T><P>0.0023635337968221</P></Row>
<Row><S>AL</S><T>AL590004</T><P>0.0025406775019662</P></Row>
<Row><S>AL</S><T>AL590005</T><P>0.0006525498178311</P></Row>
<Row><S>AL</S><T>AL590006</T><P>0.0028529702133123</P></Row>
<Row><S>AL</S><T>AL591019</T><P>0.0026282963312113</P></Row>
<Row><S>AL</S><T>AL591020</T><P>0.0008259488968758</P></Row>
<Row><S>AL</S><T>AL591024</T><P>0.0020826162667844</P></Row>
<Row><S>AL</S><T>AL591026</T><P>0.0021011677692476</P></Row>
<Row><S>AL</S><T>AL591027</T><P>0.0019249563672998</P></Row>
<Row><S>AL</S><T>AL591033</T><P>0.0025434331375939</P></Row>
<Row><S>AL</S><T>AL591040</T><P>0.0004438032780002</P></Row>
<Row><S>AL</S><T>AL591043</T><P>0.0014828861307719</P></Row>
<Row><S>AL</S><T>AL591047</T><P>0.0014612013953725</P></Row>
<Row><S>AL</S><T>AL591049</T><P>0.0007540620360289</P></Row>
<Row><S>AL</S><T>AL592002</T><P>0.0021932661643223</P></Row>
<Row><S>AL</S><T>AL592003</T><P>0.0005170087447898</P></Row>
<Row><S>AL</S><T>AL592004</T><P>0.0018069314461722</P></Row>
<Row><S>AL</S><T>AL592005</T><P>0.0017333683942615</P></Row>
<Row><S>AL</S><T>AL592006</T><P>0.0046394625241771</P></Row>
<Row><S>AL</S><T>AL592007</T><P>0.0027360668623654</P></Row>
<Row><S>AL</S><T>AL592008</T><P>0.0019603004623935</P></Row>
<Row><S>AL</S><T>AL592009</T><P>0.0006114496365902</P></Row>
<Row><S>AL</S><T>AL592010</T><P>0.0012508589710086</P></Row>
<Row><S>AL</S><T>AL592011</T><P>0.0008150983061701</P></Row>
<Row><S>AL</S><T>AL593001</T><P>0.0013890856277639</P></Row>
<Row><S>AL</S><T>AL593002</T><P>0.000884877233699</P></Row>
<Row><S>AL</S><T>AL593003</T><P>0.0021474835500632</P></Row>
<Row><S>AL</S><T>AL593004</T><P>0.0005152416023158</P></Row>
<Row><S>AL</S><T>AL593005</T><P>0.0015392923887417</P></Row>
<Row><S>AL</S><T>AL594002</T><P>0.0021934617653126</P></Row>
<Row><S>AL</S><T>AL594003</T><P>0.0010207185513072</P></Row>
<Row><S>AL</S><T>AL594004</T><P>0.0021295688147924</P></Row>
<Row><S>AL</S><T>AL594005</T><P>0.0018917510898229</P></Row>
<Row><S>AL</S><T>AL595001</T><P>0.0035982997193319</P></Row>
<Row><S>AL</S><T>AL595002</T><P>0.0002267182374218</P></Row>
<Row><S>AL</S><T>AL595003</T><P>0.0009128135068571</P></Row>
<Row><S>AL</S><T>AL596001</T><P>0.0017925335827341</P></Row>
<Row><S>AL</S><T>AL596002</T><P>0.0002833138372856</P></Row>
<Row><S>AL</S><T>AL596003</T><P>0.0020661580991117</P></Row>
<Row><S>AL</S><T>AL596004</T><P>0.0010862933958886</P></Row>
<Row><S>AL</S><T>AL596005</T><P>0.0023367843450398</P></Row>
<Row><S>AL</S><T>AL596006</T><P>0.0007950366018632</P></Row>
<Row><S>AL</S><T>AL596007</T><P>0.000585432697221</P></Row>
<Row><S>AL</S><T>AL596008</T><P>0.0003643302362679</P></Row>
<Row><S>AL</S><T>AL597001</T><P>0.0007751088183656</P></Row>
<Row><S>AL</S><T>AL597002</T><P>0.0013073917066019</P></Row>
<Row><S>AL</S><T>AL597003</T><P>0.0028270118785003</P></Row>
<Row><S>AL</S><T>AL597004</T><P>0.0020061991837708</P></Row>
<Row><S>AL</S><T>AL597005</T><P>0.0010121855406385</P></Row>
<Row><S>AL</S><T>AL598001</T><P>0.0029580296557835</P></Row>
<Row><S>AL</S><T>AL598002</T><P>0.0009473974017025</P></Row>
<Row><S>AL</S><T>AL598003</T><P>0.0002712330514887</P></Row>
<Row><S>AL</S><T>AL598004</T><P>0.0020366739451155</P></Row>
<Row><S>AL</S><T>AL598005</T><P>0.0006825465896353</P></Row>
<Row><S>AL</S><T>AL599001</T><P>0.0040749773383713</P></Row>
<Row><S>AL</S><T>AL599002</T><P>0.0003827874473696</P></Row>
<Row><S>AL</S><T>AL599003</T><P>0.0005887516085084</P></Row>
<Row><S>AL</S><T>AL600001</T><P>0.0010829080184353</P></Row>
<Row><S>AL</S><T>AL600002</T><P>0.0008613682153132</P></Row>
<Row><S>AL</S><T>AL600003</T><P>0.0006340066095264</P></Row>
<Row><S>AL</S><T>AL600004</T><P>0.0006573195094242</P></Row>
<Row><S>AL</S><T>AL607017</T><P>0.0027570110609661</P></Row>
<Row><S>AL</S><T>AL610002</T><P>0.001401134394223</P></Row>
<Row><S>AL</S><T>AL610003</T><P>0.0036872385207648</P></Row>
<Row><S>AL</S><T>AL610008</T><P>0.0007452338277712</P></Row>
<Row><S>AL</S><T>AL610010</T><P>0.0033158642368349</P></Row>
<Row><S>AL</S><T>AL610012</T><P>0.000469712354187</P></Row>
<Row><S>AL</S><T>AL610014</T><P>0.0004950969047958</P></Row>
<Row><S>AL</S><T>AL610015</T><P>0.0007286082862412</P></Row>
<Row><S>AL</S><T>AL610016</T><P>0.000747059112164</P></Row>
<Row><S>AL</S><T>AL610017</T><P>0.0060891745428126</P></Row>
<Row><S>AL</S><T>AL610018</T><P>0.0060308177164524</P></Row>
<Row><S>AL</S><T>AL610019</T><P>0.0009665755062409</P></Row>
<Row><S>AL</S><T>AL610020</T><P>0.0013246669106286</P></Row>
<Row><S>AL</S><T>AL611002</T><P>0.0006117495084501</P></Row>
<Row><S>AL</S><T>AL611004</T><P>0.0015893193526528</P></Row>
<Row><S>AL</S><T>AL612004</T><P>0.0008832033048979</P></Row>
<Row><S>AL</S><T>AL612008</T><P>0.0018681706949684</P></Row>
<Row><S>AL</S><T>AL614001</T><P>0.0010142653783989</P></Row>
<Row><S>AL</S><T>AL615001</T><P>0.0060866709183004</P></Row>
<Row><S>AL</S><T>AL615006</T><P>0.0023844000789254</P></Row>
<Row><S>AL</S><T>AL615007</T><P>0.0038333553961818</P></Row>
<Row><S>AL</S><T>AL615008</T><P>0.0015290407937757</P></Row>
<Row><S>AL</S><T>AL615009</T><P>0.0016362480063389</P></Row>
<Row><S>AL</S><T>AL615011</T><P>0.0006076636606887</P></Row>
<Row><S>AL</S><T>AL615012</T><P>0.0007975025176487</P></Row>
<Row><S>AL</S><T>AL615013</T><P>0.0013098739210192</P></Row>
<Row><S>AL</S><T>AL616001</T><P>0.0023617173023433</P></Row>
<Row><S>AL</S><T>AL616004</T><P>0.0013113745461381</P></Row>
<Row><S>AL</S><T>AL616005</T><P>0.0048247829219848</P></Row>
<Row><S>AL</S><T>AL616006</T><P>0.0004804245777031</P></Row>
